default: &default
    working_directory: /home/circleci/project
    docker:
        - image: circleci/node:8-stretch-browsers-legacy

version: 2
jobs:
    checkout:
      <<: *default
      steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths: project

    build:
        <<: *default
        steps:
            - attach_workspace:
                at: /home/circleci
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: NPM dependencies install
                command: npm i
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - persist_to_workspace:
                root: /home/circleci
                paths: project

    build_npm:
        <<: *default
        steps:
            - attach_workspace:
                at: /home/circleci
            - run:
                name: Make npm bundle
                command: npm run build:npm

    built_branch:
        <<: *default
        steps:
            - attach_workspace:
                at: /home/circleci
            - add_ssh_keys:
                fingerprints:
                    - "70:a9:87:33:e4:bd:6f:01:a3:b0:05:1d:29:e4:25:85"
            - run:
                name: build npm branch (built)
                command: |
                    env |sort
                    mv project/npm_build /tmp
                    rm -Rf project/*
                    mv /tmp/npm_build project

workflows:
    version: 2

    publish:
        jobs:
            - checkout:
                filters:
                    branches:
                        only: /(^master)/
            - build:
                requires:
                    - checkout
            - build_npm:
                filters:
                    branches:
                        only: /(^master)/
                requires:
                    - build
