default: &default
    working_directory: /home/circleci/project
    docker:
        - image: circleci/node:8-stretch-browsers-legacy

version: 2
jobs:
    checkout:
      <<: *default
      steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths: project

    build:
        <<: *default
        steps:
            - attach_workspace:
                at: /home/circleci
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: NPM dependencies install
                command: npm i
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - persist_to_workspace:
                root: /home/circleci
                paths: project

    publish_npm:
        <<: *default
        steps:
            - attach_workspace:
                at: /home/circleci
            - add_ssh_keys:
                fingerprints:
                    - "70:a9:87:33:e4:bd:6f:01:a3:b0:05:1d:29:e4:25:85"
            - run: mkdir ~/.ssh && ssh-keyscan "github.com"  >> ~/.ssh/known_hosts
            - run:
                name: Make npm bundle
                command: npm run build:npm
            - run:
                name: Publish bundle
                command: |
                    git config --global user.name "CircleCI Automation"
                    git config --global user.email "yuri.reis@msn.com"
                    mv $CIRCLE_WORKING_DIRECTORY/npm_dist /tmp
                    git checkout -f built
                    rm -Rf $CIRCLE_WORKING_DIRECTORY/*
                    mv /tmp/npm_dist/* $CIRCLE_WORKING_DIRECTORY
                    cd $CIRCLE_WORKING_DIRECTORY && git add -A && git commit --amend --no-edit && git push -f origin built

workflows:
    version: 2

    publish:
        jobs:
            - checkout:
                filters:
                    branches:
                        only: /(^master)/
            - build:
                requires:
                    - checkout
            - publish_npm:
                filters:
                    branches:
                        only: /(^master)/
                requires:
                    - build
